### ISSUE TITLE
Why no `use-package`?

### ISSUE THREAD

**Issue by PauloPhagula** [munen/emacs.d#5]
Hi,

I'm just curious with why you don't use `use-package`. I wonder if you get perf gains from going sans `use-package` or if you just don't find a good reason or time to do the switch.

Cheers

**Comment by munen** [comment]
Hi @dareenzo 

Thank you for your question. The reason is pretty simple: First of all, when I started out with this config, there was no `use-package`. And now, I don't see a reason to switch. In my understanding, the main rationale use `use-package` is to group together related changes for packages which is a good thing to do. Having said that, using Org mode you get similar semantics with additional options for documentation.

Best regards and good health
